;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	c-electric-brace
	c-electric-colon
	c-electric-delete-forward
	c-electric-lt-gt
	c-electric-paren
	c-electric-semi&comma
	delete-horizontal-space
	easy-kill
	electric-newline-and-maybe-indent
	ess-smart-comma
	ess-yank
	insert-register
	kill-region
	org-end-of-line
	org-self-insert-command
	phi-search
	))

(setq mc/cmds-to-run-once
      '(
	ace-window
	ava/multiple-cursors-hydra/mc/edit-beginnings-of-lines
	ava/multiple-cursors-hydra/mc/insert-numbers
	ava/multiple-cursors-hydra/mc/mark-all-like-this-and-exit
	ava/multiple-cursors-hydra/mc/mark-all-symbols-like-this-and-exit
	ava/multiple-cursors-hydra/mc/mark-all-symbols-like-this-in-defun-and-exit
	ava/multiple-cursors-hydra/mc/mark-next-like-this
	ava/multiple-cursors-hydra/mc/mark-previous-like-this
	ava/multiple-cursors-hydra/mc/skip-to-next-like-this
	ava/multiple-cursors-hydra/mc/skip-to-previous-like-this
	ava/multiple-cursors-hydra/mc/unmark-next-like-this
	ava/multiple-cursors-hydra/mc/unmark-previous-like-this
	ava/multiple-cursors-hydra/mc/vertical-align
	dabbrev-expand
	helm-M-x
	switch-window
	undo-tree-visualize
	))
