#Basics
if-shell "infocmp -x tmux-256color >/dev/null 2>&1" "set -g default-terminal tmux-256color" "set -g default-terminal xterm-256color"
set -g history-limit 100000

#Use ` as default prefix
unbind C-b
set -g prefix `
bind-key ` send-prefix

#Terminal emulator window title
set -g set-titles on
set -g set-titles-string "#S:#I:#P #W"

#Reload config
bind r source-file ~/.tmux.conf \; display "Config reloaded!"

#Pane creation
bind h split-window -v -c '#{pane_current_path}'
bind v split-window -h -c '#{pane_current_path}'

#Pane layout
bind '\' select-layout even-vertical
bind - select-layout even-horizontal

#Status bar
set -g status-justify left
set -g status-left "[#h %H:%M %Y-%h-%d]"
set -g status-left-length 100
set -g status-right ""

#Window renaming
setw -g automatic-rename off

#Colors
set -g status-bg black
set -g status-fg white
set-option -gw window-status-current-style fg=green,bold

#Alert on any window bell
set -g bell-action any

#Kill window/pane
bind-key k confirm-before -p "kill-window #W? (y/n)" kill-window
bind-key x kill-pane

#Join pane
bind-key j command-prompt -p "join pane from:" "join-pane -s '%%'"
